###########################

Levels:

  1:
    xp required: 100

  2:
    xp required: 110

  3:
    xp required: 121

  4:
    xp required: 133

  5:
    xp required: 146

  6:
    xp required: 161

  7:
    xp required: 177

  8:
    xp required: 194

  9:
    xp required: 214

  10:
    xp required: 235

  11:
    xp required: 259

  12:
    xp required: 285

  13:
    xp required: 313

  14:
    xp required: 345

  15:
    xp required: 379

  16:
    xp required: 417

  17:
    xp required: 459

  18:
    xp required: 505

  19:
    xp required: 555

  20:
    xp required: 611

  21:
    xp required: 672

  22:
    xp required: 740

  23:
    xp required: 814

  24:
    xp required: 895

  25:
    xp required: 984

  26:
    xp required: 1083

  27:
    xp required: 1191

  28:
    xp required: 1310

  29:
    xp required: 1442

  30:
    xp required: 1586

  31:
    xp required: 1744

  32:
    xp required: 2111

  33:
    xp required: 2322

  34:
    xp required: 2554

  35:
    xp required: 2810

  36:
    xp required: 3091

  37:
    xp required: 3400

  38:
    xp required: 3740

  39:
    xp required: 4114

  40:
    xp required: 4525

  41:
    xp required: 4978

  42:
    xp required: 5476

  43:
    xp required: 6024

  44:
    xp required: 6626

  45:
    xp required: 7289

  46:
    xp required: 8017

  47:
    xp required: 8819

  48:
    xp required: 9701

  49:
    xp required: 10671

  50:
    xp required: 11739
